language: java
cache:
  directories:
    - .autoconf
    - $HOME/.m2
script:
  # to avoid build errors due to excessive logging
  - mvn dependency:go-offline -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B
  - mvn clean install
