/**
 * Copyright (c) 2023, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import { IdentifiableComponentInterface } from "@wso2is/core/models";
import React, { FunctionComponent, ReactElement } from "react";
import { CustomTextPreferenceConstants } from "../../../../constants/custom-text-preference-constants";
import useBrandingPreference from "../../../../hooks/use-branding-preference";

/**
 * Proptypes for the totp fragment of login screen skeleton.
 */
export type TOTPInterface = IdentifiableComponentInterface;

/**
 * TOTP fragment component for the branding preview of Sign In box.
 *
 * @param props - Props injected to the component.
 * @returns TOTP fragment component.
 */
const TOTP: FunctionComponent<TOTPInterface> = (props: TOTPInterface): ReactElement => {
    const { ["data-componentid"]: componentId } = props;

    const { i18n } = useBrandingPreference();

    return (
        <div data-componentid={ componentId }>
            <h3 className="ui header text-center">
                { i18n(CustomTextPreferenceConstants.TEXT_BUNDLE_KEYS.TOTP.HEADING, "Verify Your Identity") }
            </h3>

            <div className="segment-form">
                <form method="post" id="totpForm" className="ui large form otp-form">
                    <p className="text-center" id="instruction">
                        Enter the verification code generated by your authenticator app.
                    </p>

                    <div className="equal width fields">
                        <div className="field mt-5">
                            <input
                                className="text-center p-3"
                                id="pincode-1"
                                name="pincode-1"
                                placeholder="·"
                                maxLength={ 1 }
                                autoComplete="off"
                            />
                        </div>
                        <div className="field mt-5">
                            <input
                                className="text-center p-3"
                                id="pincode-2"
                                name="pincode-2"
                                placeholder="·"
                                maxLength={ 1 }
                                autoComplete="off"
                            />
                        </div>
                        <div className="field mt-5">
                            <input
                                className="text-center p-3"
                                id="pincode-3"
                                name="pincode-3"
                                placeholder="·"
                                maxLength={ 1 }
                                autoComplete="off"
                            />
                        </div>
                        <div className="field mt-5">
                            <input
                                className="text-center p-3"
                                id="pincode-4"
                                name="pincode-4"
                                placeholder="·"
                                maxLength={ 1 }
                                autoComplete="off"
                            />
                        </div>
                        <div className="field mt-5">
                            <input
                                className="text-center p-3"
                                id="pincode-5"
                                name="pincode-5"
                                placeholder="·"
                                maxLength={ 1 }
                                autoComplete="off"
                            />
                        </div>
                        <div className="field mt-5">
                            <input
                                className="text-center p-3"
                                id="pincode-6"
                                name="pincode-6"
                                placeholder="·"
                                maxLength={ 1 }
                                autoComplete="off"
                            />
                        </div>
                    </div>
                    <div className="ui divider hidden"></div>
                    <div className="ui divider hidden"></div>
                    <div>
                        <input
                            type="submit"
                            id="subButton"
                            value="Continue"
                            className="ui primary fluid large button"
                        />
                    </div>
                    <div className="text-center mt-1"></div>
                </form>
            </div>
            <div className="ui" id="enrol-msg">
                Haven&apos;t setup your TOTP authenticator yet? <a>Contact support</a>
            </div>
        </div>
    );
};

/**
 * Default props for the component.
 */
TOTP.defaultProps = {
    "data-componentid": "branding-preview-totp-fragment"
};

export default TOTP;
