/**
 * Copyright (c) 2024, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
import { smsProvidersNS } from "../../../models";

export const smsProviders: smsProvidersNS = {
    heading: "SMS Provider",
    subHeading: "Configure a SMS provider to send SMS to your users.",
    description: "Configure the SMS provider settings according to your SMS provider.",
    info: "You can customize the SMS content using <1>SMS Templates</1>.",
    updateButton: "Update",
    sendTestSMSButton: "Send Test SMS",
    goBack: "Go back to Email & SMS",
    confirmationModal: {
        assertionHint: "Please confirm your action.",
        content: "If you delete this configuration, you will not receive SMS." +
            "Please proceed with caution.",
        header: "Are you sure?",
        message: "This action is irreversible and will permanently delete the SMS provider configurations."
    },
    dangerZoneGroup: {
        header: "Danger Zone",
        revertConfig: {
            heading: "Delete Configurations",
            subHeading: "This action will delete sms provider configurations. " +
                "Once deleted, you will not receive SMS.",
            actionTitle: "Delete"
        }
    },
    form: {
        twilio: {
            subHeading: "Twilio Settings",
            accountSID: {
                label: "Twilio Account SID",
                placeholder: "Enter the Twilio account SID",
                hint: "Twilio account string identifier which act as username for the account"
            },
            authToken: {
                label: "Twilio Auth Token",
                placeholder: "Enter the Twilio auth token",
                hint: "The access token generated by the Twilio auth server "
            },
            sender: {
                label: "Sender",
                placeholder: "Enter the sender phone number",
                hint: "Phone number of the sender."
            },
            validations: {
                required: "This field cannot be empty"
            }
        },
        vonage: {
            subHeading: "Vonage Settings",
            accountSID: {
                label: "Vonage API Key",
                placeholder: "Enter the Vonage API key",
                hint: "Vonage API Key which act as username for the account."
            },
            authToken: {
                label: "Vonage API Secret",
                placeholder: "Enter the Vonage API Secret",
                hint: "The API Secret generated by the Vonage auth server."
            },
            sender: {
                label: "Sender",
                placeholder: "Enter the sender phone number",
                hint: "Phone number of the sender."
            },
            validations: {
                required: "This field cannot be empty"
            }
        },
        custom: {
            subHeading: "Custom Settings",
            providerName: {
                label: "SMS Provider Name",
                placeholder: "Enter the SMS provider name",
                hint: "The name of the SMS provider."
            },
            providerUrl: {
                label: "SMS Provider URL",
                placeholder: "Enter the sms provider URL",
                hint: "The URL of the SMS provider."
            },
            httpMethod: {
                label: "HTTP Method",
                placeholder: "POST",
                hint: "The HTTP method of the API request. (Default is POST)"
            },
            contentType: {
                label: "Content Type",
                placeholder: "JSON",
                hint: "The content type of the API request. Accepted values are 'FORM' or 'JSON'"
            },
            headers: {
                label: "Headers",
                placeholder: "authorisation: Bearer {{token}}",
                hint: "Comma seperated list of HTTP headers to be included in the SMS API request."
            },
            payload: {
                label: "Payload Template",
                placeholder: "{\"content\": {{body}}, \"to\": {{mobile}} }",
                hint: "The payload template of the API request. Use {{body}} to represent the generated SMS body. Use {{mobile}} to represent the mobile number."
            },
            key: {
                label: "SMS Provider Auth Key",
                placeholder: "Enter the SMS provider auth key",
                hint: "Any authentication key that needs to be send as HTTP header."
            },
            secret: {
                label: "SMS Provider Auth Secret",
                placeholder: "Enter the SMS provider auth secret",
                hint: "Any authentication secret that needs to be send as HTTP header."
            },
            sender: {
                label: "Sender",
                placeholder: "Enter the sender",
                hint: "The SMS senders identification (phone number or name)."
            },
            validations: {
                required: "This field cannot be empty",
                methodInvalid: "The HTTP method is invalid",
                contentTypeInvalid: "The content type is invalid"
            }
        }
    },
    notifications: {
        getConfiguration: {
            error: {
                message: "Error Occurred",
                description: "Error retrieving the sms provider configurations."
            }
        },
        deleteConfiguration: {
            error: {
                message: "Error Occurred",
                description: "Error deleting the sms provider configurations."
            },
            success: {
                message: "Revert Successful",
                description: "Successfully reverted the sms provider configurations."
            }
        },
        updateConfiguration: {
            error: {
                message: "Error Occurred",
                description: "Error updating the sms provider configurations."
            },
            success: {
                message: "Update Successful",
                description: "Successfully updated the sms provider configurations."
            }
        }
    }
};
